#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [[ "$RUBY_VERSION" == "1.8" ]]; then
  echo "ERROR: This quickstart is not compatible with Ruby 1.8"
  echo "ERROR: Please use ruby-1.9 or ruby-2.0 application type."
  exit 1
fi

source $OPENSHIFT_CARTRIDGE_SDK_BASH
source ${OPENSHIFT_RUBY_DIR}/lib/ruby_context

pushd ${OPENSHIFT_REPO_DIR} >/dev/null
if [[ -f .openshift/markers/force_clean_build && "$RAILS_ENV" == "development" ]]
then
  echo "bundle install --path ./vendor/bundle"
  ruby_with_nodejs_context "bundle install --path ./vendor/bundle"
fi
popd > /dev/null